### ISSUE TITLE
Build error after make fetch

### ISSUE THREAD

**Issue by begriffs** [jpouellet/signify-osx#5]
If I clone this repo and run `make` it works fine. But if I do `make fetch` and then try `make` I get an error:

```sh
sed -e 's/hashinc/sha2.h/g' \
	    -e 's/HASH/SHA256/g' \
	    -e 's/SHA[0-9][0-9][0-9]_CTX/SHA2_CTX/g' src/lib/libc/hash/helper.c > src/lib/libc/hash/sha256hl.c
sed -e 's/hashinc/sha2.h/g' \
	    -e 's/HASH/SHA512/g' \
	    -e 's/SHA[0-9][0-9][0-9]_CTX/SHA2_CTX/g' src/lib/libc/hash/helper.c > src/lib/libc/hash/sha512hl.c
sed -e 's/hashinc/sha2.h/g' \
	    -e 's/HASH/SHA512_256/g' \
	    -e 's/SHA512_256_CTX/SHA2_CTX/g' src/lib/libc/hash/helper.c > src/lib/libc/hash/sha512_256hl.c
make: *** No rule to make target `src/usr.bin/signify/smult_curve25519_ref.c', needed by `signify'.  Stop.
```

I'm on os x 10.11.6

**Comment by jpouellet** [comment]
Yeah, stuff changed upstream.

I'll look at it after the weekend cause I wanna make sure I don't miss anything and don't have time to do a careful update right now.

Thanks for pinging me about it.

**Comment by begriffs** [comment]
No rush, thanks for taking a look.

**Comment by jpouellet** [comment]
Sync'd with upstream. Should be good now. Sorry it took so long.

**Comment by jpouellet** [comment]
Actually, you said you were on 10.11.6, which is before a bunch of previously openbsd-specific functions were added to macOS's libc in 10.12. Are you still on 10.11?

**Comment by begriffs** [comment]
> Sync'd with upstream. Should be good now. Sorry it took so long.

No problem, thank you for your help.

> Are you still on 10.11?

I'm on 10.13.6 now. Wish I had a machine with the older version so I
could help you test.
